# Generated by Django 4.1.5 on 2023-01-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_arquivo_final_alter_jobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='arquivo_final',
        ),
    ]
